In [1]:
import os
os.listdir("./")

['.ipynb_checkpoints',
 'comp4_det_val_aeroplane.txt',
 'comp4_det_val_bicycle.txt',
 'comp4_det_val_boat.txt',
 'comp4_det_val_bottle.txt',
 'comp4_det_val_bus.txt',
 'comp4_det_val_car.txt',
 'comp4_det_val_chair.txt',
 'comp4_det_val_diningtable.txt',
 'comp4_det_val_motorbike.txt',
 'comp4_det_val_sofa.txt',
 'comp4_det_val_train.txt',
 'comp4_det_val_tvmonitor.txt',
 'Untitled.ipynb']

In [12]:
import numpy as np
from collections import OrderedDict 
res = OrderedDict()
for file in os.listdir("./"):
    if file.endswith(".txt"):
        label = file.split("_")[3].split(".")[0]
        res_tmp = []
        with open(file, "r") as f:
            for lines in f:
                #print(lines.split(" ")[1], lines.split(" ")[6])
                res_tmp.append([float(lines.split(" ")[1]), int(lines.split(" ")[6])])
        res[label] = np.array(res_tmp)

In [19]:
np.flip(res["car"][res["car"][:, 0].argsort()], 0)

array([[ 1.   ,  2.   ],
       [ 1.   , 22.   ],
       [ 1.   ,  3.   ],
       [ 1.   , 23.   ],
       [ 1.   , 23.   ],
       [ 1.   , 23.   ],
       [ 1.   ,  3.   ],
       [ 1.   , 23.   ],
       [ 1.   ,  2.   ],
       [ 1.   ,  3.   ],
       [ 1.   ,  3.   ],
       [ 1.   ,  2.   ],
       [ 1.   , 10.   ],
       [ 1.   ,  2.   ],
       [ 1.   , 22.   ],
       [ 1.   , 23.   ],
       [ 1.   ,  2.   ],
       [ 1.   , 24.   ],
       [ 1.   , 22.   ],
       [ 1.   ,  3.   ],
       [ 1.   , 24.   ],
       [ 1.   ,  2.   ],
       [ 1.   , 23.   ],
       [ 1.   , 22.   ],
       [ 1.   , 23.   ],
       [ 1.   , 23.   ],
       [ 1.   , 23.   ],
       [ 1.   ,  3.   ],
       [ 1.   , 23.   ],
       [ 1.   , 23.   ],
       [ 1.   , 23.   ],
       [ 1.   , 14.   ],
       [ 1.   ,  2.   ],
       [ 1.   , 22.   ],
       [ 1.   ,  4.   ],
       [ 1.   ,  2.   ],
       [ 1.   ,  2.   ],
       [ 1.   , 23.   ],
       [ 1.   ,  3.   ],
       [ 1.   ,  2.   ],


In [26]:
for label in res:
    print(label)
    view_point = np.zeros(shape=(24))
    for obj in res[label]:
        view_point[int(obj[1]) - 1] += obj[0]
    print(view_point.argsort())

aeroplane
[10 12 13  8 11 16  9 14 21  1 17 18  6 15  0  5  7 19  2  4 22  3 20 23]
bicycle
[13 12 11 10 22 18  5 15  9  8  7 14  2  1  0  6  3 20 16 23  4 21 19 17]
boat
[13 12  6  9 14  0 11  8  4 17 16 19  5  1 18 10  7 20  2 15 22 21  3 23]
bottle
[13 12  9 10 16 15 14  7  8 11 17  5  4 19  6 18 20 21 22  1  3  2  0 23]
bus
[13 15  5 16 14  6 18 17 20  8  7 12 10  9 11  3  4 19 21  2  0 23  1 22]
car
[15 11  8  5 18 10  6 13 16 17  4 14  7 12  9 19  3  0 20 21 23  2  1 22]
chair
[13 12  8 10  9  6  7 17 16 11 14  5 19 18  4 15  3 20  1 22  2 21  0 23]
diningtable
[11 13 12 14 16 15 10  8  9  7 17  6 18 20  5 19  4  1  3 22  0  2 21 23]
motorbike
[13 12 11 15 14  9 10  5  0 16  7  8  4  6 19  1 23 22 18 17 20  3 21  2]
sofa
[11 15 13 12  9 16 10  8  5  7 14  4  6 17 18 20  3 19  2  1 21 22  0 23]
train
[13 16  8 14  5  9 12 15  4 17  6 19 11 18 10  3  7 20  2 21  1  0 22 23]
tvmonitor
[10 13  5 12  9 16 15 17 11  8  6 18  7 14  4 20 19  3 21  2 22  1  0 23]
